import { Button, VerticalBox } from "std-widgets.slint";

component myText inherits Text {
    font-family: "Helvetica Neue";
    font-weight: 400;
    font-size: 24px; 
}

export component MainWindow inherits Window {
    title: @tr("ttt");
    width: 600px;
    height: 400px;

    HorizontalLayout {
        height: 50px;
        y: 27px;
        alignment: space-between;
        padding-left: 20px;
        padding-right: 20px;
        myText { 
            text: "ttt"; 
            font-weight: 700;
            font-size: 18px;
            letter-spacing: -0.5px;
        }
    }
}